# Generated by Django 5.1.3 on 2024-12-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_price', to='home.roomtype'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_types',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.roomtype'),
        ),
    ]
