# Generated by Django 5.1.3 on 2024-12-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_room_price_alter_room_room_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_types',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='home.roomtype'),
        ),
    ]
