# Generated by Django 5.1.3 on 2024-12-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_room_is_available_remove_room_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fullname',
        ),
    ]
