# Generated by Django 5.1.3 on 2024-12-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_room_price_alter_room_room_types'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
