# Generated by Django 5.1.3 on 2024-12-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_employee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
